version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - pip install --upgrade pip
      - pip install --upgrade awscli aws-sam-cli
      - pip install poetry
  build:
    commands:
      - cd "${PROJECT_SUBFOLDER}"
      - poetry export --without-hashes --format=requirements.txt --output=src/requirements.txt
      - . pipeline/assume-role.sh "${ENV_PIPELINE_EXECUTION_ROLE}" test-package
      # trigger the integration tests here
      - echo 'Running integration tests'
