version = 0.1

[1]
[1.global]
[1.global.parameters]
stack_name = "uni-prop-dev-contracts"
s3_prefix = "uni-prop-dev-contracts"
s3_bucket = "aws-sam-cli-managed-production-pip-artifactsbucket-6qzfstheu2ys"
region = "us-east-1"

[1.deploy]
[1.deploy.parameters]
template = "packaged-testing.yaml"
fail_on_empty_changeset = false
capabilities = "CAPABILITY_IAM CAPABILITY_AUTO_EXPAND"
parameter_overrides = "Stage=development"

# ############################################## #

[2]
[2.global]
[2.global.parameters]
stack_name = "uni-prop-prop-contracts"
s3_prefix = "uni-prop-prop-contracts"
s3_bucket = "aws-sam-cli-managed-production-pip-artifactsbucket-6qzfstheu2ys"
region = "us-east-1"

[2.deploy]
[2.deploy.parameters]
template = "packaged-prod.yaml"
fail_on_empty_changeset = false
capabilities = "CAPABILITY_IAM CAPABILITY_AUTO_EXPAND"
parameter_overrides = "Stage=\"production\""

# ############################################## #

[pipeline]
[pipeline.deploy]
[pipeline.deploy.parameters]
stack_name = "uni-prop-contracts-pipeline-sneha"
s3_prefix = "uni-prop-contracts-pipeline-sneha"
resolve_s3 = true
fail_on_empty_changeset = false
template = "codepipeline.yaml"
capabilities = "CAPABILITY_IAM"
